# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
#  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "public_network", bridge: "enp2s0"
#  config.vm.synced_folder "./sync", "/home/vagrant/sync"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1280"
     vb.cpus = 2
   end

   config.vm.provision "shell", inline: <<-SHELL
	sudo yum update -y
	curl -sSL https://get.docker.com/ | sudo sh
	sudo usermod -aG docker vagrant
	sudo service docker start
	sudo chkconfig docker on
	sudo yum -y install epel-release
	sudo yum -y install python-pip
	sudo pip install -U docker-compose
   SHELL
end
